// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUukcPfkE1xRMp2KPB4hQTDfQWkc8oX8',
    appId: '1:247107784446:web:dff327dafd846b7d891faf',
    messagingSenderId: '247107784446',
    projectId: 'flutter-todolist-project',
    authDomain: 'flutter-todolist-project.firebaseapp.com',
    storageBucket: 'flutter-todolist-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjnKcJ6W4-0n34bq4akAuM8jQAw9cizU',
    appId: '1:247107784446:android:18eba0983c8b030e891faf',
    messagingSenderId: '247107784446',
    projectId: 'flutter-todolist-project',
    storageBucket: 'flutter-todolist-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqf7VYhdvVeTXhg0JWe6fxSvUdSFRVs8',
    appId: '1:247107784446:ios:c211da168f1070bc891faf',
    messagingSenderId: '247107784446',
    projectId: 'flutter-todolist-project',
    storageBucket: 'flutter-todolist-project.firebasestorage.app',
    iosClientId: '247107784446-peto6ngpopmf4ritllvusug98lt8teki.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttodlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqf7VYhdvVeTXhg0JWe6fxSvUdSFRVs8',
    appId: '1:247107784446:ios:c211da168f1070bc891faf',
    messagingSenderId: '247107784446',
    projectId: 'flutter-todolist-project',
    storageBucket: 'flutter-todolist-project.firebasestorage.app',
    iosClientId: '247107784446-peto6ngpopmf4ritllvusug98lt8teki.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttodlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYUukcPfkE1xRMp2KPB4hQTDfQWkc8oX8',
    appId: '1:247107784446:web:c1d97e5eef647249891faf',
    messagingSenderId: '247107784446',
    projectId: 'flutter-todolist-project',
    authDomain: 'flutter-todolist-project.firebaseapp.com',
    storageBucket: 'flutter-todolist-project.firebasestorage.app',
  );

}